### ISSUE TITLE
Functional tests with extra containers

### ISSUE THREAD

**Issue by wojas** [PowerDNS/pdns-builder#24]
Separate the install test step to allow running multiple containers.

Currently we run the install tests as part of the multi-stage build. This works very well for simple install tests, but does not allow running extra containers for the duration of the tests.

In addition to the current install tests, we should support a way to run tests with multiple containers using the just built container.

Use cases:

- Run a database container to test against
- Test with multiple instances on different IP addresses

In its simplest form, this means:

- Set an environment variable with the name or tag of the built image 
- Execute an optional post-build-tests shell script from `builder-support/`
- Fail the build if that script returns a non-zero exit code

This post-build-tests script can launch extra containers and run a series of tests inside the final (install test) container. These tests would be skipped when install tests are skipped (partial builds).

Cc @pieterlexis @Habbie

**Comment by pieterlexis** [comment]
yes! PowerDNS/pdns needs this! I also have another item for this list:

* Allow running tests even when `-m` is specified
