### ISSUE TITLE
Remove RHEL/CentOS Server Edition builds

### ISSUE THREAD

**Issue by istiak101** [PowerDNS/pdns-builder#56]
After RHEL/CentOS 7 there is no separate server edition but still server edition rpm for RHEL/CentOS being built and served from PDNS repository. Removing this build type from repository will free up around 14.4 GB storage and save resources from future builds. I am bit surprised anyone didn't notice this.

refs: https://ftp.redhat.com/redhat/linux/enterprise/

**Comment by Habbie** [comment]
Thank you! Although you can't see it this way, https://repo.powerdns.com/centos/x86_64/ is 3 dirs and 3 symlinks. We are not wasting disk space on server editions.

Closing this.
