### ISSUE TITLE
Redhat 9 build support

### ISSUE THREAD

**Issue by istiak101** [PowerDNS/pdns-builder#60]
Redhat 9 and 1:1 forks are now GA for some time. Any plan to add support for it in PowerDNS official repository?
https://repo.powerdns.com/el/x86_64/

https://developers.redhat.com/articles/2022/05/18/whats-new-red-hat-enterprise-linux-9
https://almalinux.org/blog/almalinux-9-now-available/
https://en.euro-linux.com/blog/eurolinux-9-0-released/

**Comment by Habbie** [comment]
Hi there, you posted this in the wrong repository. The right repository is https://github.com/PowerDNS/pdns/
